        const sciQ = [
            { q: "What is the SI unit of electric current?", a: "Ampere (A)", s: "The SI unit of electric current is the <strong>Ampere (A)</strong>, defined by the movement of one coulomb per second." },
            { q: "Which law states that the pressure of a fixed amount of gas varies inversely with its volume at constant temperature?", a: "Boyle's Law", s: "<strong>Boyle's Law</strong>: PV = constant (at constant temperature). P₁V₁ = P₂V₂." },
            { q: "The process of conversion of solid directly to gas without passing through the liquid state is:", a: "Sublimation", s: "<strong>Sublimation</strong> is the direct phase change from solid to gas (e.g., dry ice/camphor)." },
            { q: "What is the chemical formula of Ozone?", a: "O₃", s: "Ozone consists of three oxygen atoms: <strong>O₃</strong>. It forms a protective layer in the stratosphere." },
            { q: "Which organelle is called the 'powerhouse of the cell'?", a: "Mitochondria", s: "<strong>Mitochondria</strong> produce ATP (adenosine triphosphate) through cellular respiration." },
            { q: "What is the valency of Nitrogen?", a: "3", s: "Nitrogen has 5 valence electrons. To complete octet it gains/shares 3 electrons — valency = <strong>3</strong>." },
            { q: "Which type of lens is used in a simple microscope?", a: "Convex lens", s: "A simple microscope uses a <strong>convex (converging) lens</strong> to magnify objects." },
            { q: "The disease caused by deficiency of Vitamin B12 is:", a: "Pernicious anaemia", s: "Vitamin B12 deficiency causes <strong>Pernicious anaemia</strong>, affecting red blood cell production." },
            { q: "Which gas is produced by the reaction of zinc with dilute sulphuric acid?", a: "Hydrogen", s: "Zn + H₂SO₄ → ZnSO₄ + <strong>H₂↑</strong>. Hydrogen gas is produced." },
            { q: "What is the phenomenon called when white light splits into its constituent colours?", a: "Dispersion", s: "<strong>Dispersion</strong> occurs when white light passes through a prism, separating into VIBGYOR." },
            { q: "Which part of the human eye controls the amount of light entering?", a: "Iris", s: "The <strong>Iris</strong> is the coloured diaphragm that controls the size of the pupil, regulating light entry." },
            { q: "The hardest natural substance is:", a: "Diamond", s: "<strong>Diamond</strong> (allotrope of carbon) is the hardest known natural substance (Mohs scale: 10)." },
            { q: "Which hormone regulates blood sugar level?", a: "Insulin", s: "<strong>Insulin</strong>, secreted by beta cells of Pancreas, lowers blood glucose levels." },
            { q: "Ohm's Law in terms of resistance: if voltage doubles and current stays same, resistance:", a: "Doubles", s: "R = V/I. If V doubles and I constant, R = <strong>doubles</strong>." },
            { q: "The atomic mass of Chlorine is approximately:", a: "35.5 u", s: "Chlorine exists as Cl-35 and Cl-37 isotopes. Weighted average = <strong>35.5 u</strong>." },
            { q: "Which is the largest gland in the human body?", a: "Liver", s: "The <strong>Liver</strong> is the largest internal gland, weighing about 1.5 kg." },
            { q: "What is the principle of an electric transformer?", a: "Mutual induction", s: "A transformer works on the principle of <strong>mutual electromagnetic induction</strong>." },
            { q: "The chemical name of Baking Soda is:", a: "Sodium Bicarbonate (NaHCO₃)", s: "Baking soda = <strong>Sodium Hydrogen Carbonate (NaHCO₃)</strong>, also called Sodium Bicarbonate." },
            { q: "Which type of radiation has the highest penetrating power?", a: "Gamma (γ) rays", s: "<strong>Gamma rays</strong> have the highest penetrating power, requiring thick lead or concrete to stop." },
            { q: "The process by which a cell divides to produce two identical daughter cells is:", a: "Mitosis", s: "<strong>Mitosis</strong> produces two genetically identical daughter cells. Meiosis produces four non-identical gametes." },
            { q: "What is the pH of human blood?", a: "7.35 to 7.45", s: "Normal human blood maintains a slightly alkaline pH of <strong>7.35–7.45</strong>." },
            { q: "Which element is common to all acids?", a: "Hydrogen", s: "All acids contain <strong>Hydrogen</strong> ions (H⁺) that are released in aqueous solution." },
            { q: "Sound travels fastest in:", a: "Solids", s: "Sound travels fastest in <strong>solids</strong> because the particles are closely packed, enabling faster vibration transfer." },
            { q: "What is the formula for kinetic energy?", a: "KE = ½mv²", s: "Kinetic Energy = <strong>½ × mass × velocity²</strong>. It depends on both mass and speed." },
            { q: "Which blood cells are responsible for immunity?", a: "White Blood Cells (WBCs / Leukocytes)", s: "<strong>WBCs (Leukocytes)</strong> are the cells of the immune system that fight infections." },
            { q: "What is 'Dry Ice'?", a: "Solid Carbon Dioxide (CO₂)", s: "<strong>Dry Ice</strong> is the solid form of CO₂. It sublimates at −78.5°C without melting." },
            { q: "The law of conservation of energy states:", a: "Energy can neither be created nor destroyed", s: "Energy can only be converted from one form to another — <strong>total energy remains constant</strong>." },
            { q: "Which acid is present in ant sting?", a: "Formic acid (methanoic acid)", s: "Ant stings inject <strong>formic acid (HCOOH)</strong>, causing the burning sensation." },
            { q: "The wavelength of visible light ranges from:", a: "400 nm to 700 nm", s: "Visible light ranges from violet (<strong>~400 nm</strong>) to red (<strong>~700 nm</strong>)." },
            { q: "What is the role of chlorophyll in photosynthesis?", a: "Absorbs sunlight", s: "<strong>Chlorophyll</strong> is the green pigment that absorbs sunlight (mainly red and blue wavelengths) for photosynthesis." },
            { q: "Newton's Third Law of Motion states:", a: "Every action has an equal and opposite reaction", s: "<strong>Newton's Third Law</strong>: For every action, there is an equal and opposite reaction." },
            { q: "The unit of luminous intensity is:", a: "Candela (cd)", s: "Luminous intensity is measured in <strong>Candela (cd)</strong>, an SI base unit." },
            { q: "Rusting of iron is an example of:", a: "Oxidation (slow combustion)", s: "Rust (Fe₂O₃·xH₂O) forms by <strong>oxidation</strong> of iron in the presence of oxygen and moisture." },
            { q: "Which planet has the most moons in our solar system?", a: "Saturn (as of recent counts)", s: "As of 2024, <strong>Saturn</strong> holds the record for most confirmed moons (~146)." },
            { q: "The SI unit of pressure is:", a: "Pascal (Pa)", s: "Pressure = Force/Area. SI unit = <strong>Pascal (Pa)</strong> = N/m²." },
            { q: "What is the function of ribosomes in a cell?", a: "Protein synthesis", s: "<strong>Ribosomes</strong> are the sites of protein synthesis — they translate mRNA to assemble amino acids." },
            { q: "Which metal is liquid at room temperature?", a: "Mercury (Hg)", s: "<strong>Mercury (Hg)</strong> is the only metal that is liquid at standard room temperature (25°C)." },
            { q: "What happens to the resistance of a conductor when its temperature increases?", a: "Resistance increases", s: "For most conductors, as temperature increases, atomic vibrations increase, causing <strong>greater resistance</strong>." },
            { q: "Which organ produces bile?", a: "Liver", s: "The <strong>Liver</strong> produces bile, which is stored in the gallbladder and helps digest fats." },
            { q: "The chemical symbol for Silver is:", a: "Ag", s: "<strong>Ag</strong> comes from Latin 'Argentum' meaning Silver." },
            { q: "What is the half-life of Carbon-14?", a: "5,730 years", s: "Carbon-14 has a half-life of <strong>5,730 years</strong>, used in radiocarbon dating." },
            { q: "Which vitamin is essential for blood clotting?", a: "Vitamin K", s: "<strong>Vitamin K</strong> is necessary for the synthesis of clotting factors like prothrombin." },
            { q: "A concave mirror forms a real, inverted, diminished image when the object is:", a: "Beyond the centre of curvature", s: "When object is beyond C, concave mirror forms <strong>real, inverted, diminished</strong> image between F and C." },
            { q: "The study of fungi is called:", a: "Mycology", s: "<strong>Mycology</strong> is the branch of biology concerned with the study of fungi." },
            { q: "What is the speed of sound in air at 0°C?", a: "331 m/s", s: "Speed of sound in dry air at 0°C = <strong>331 m/s</strong>. At 25°C it is ~346 m/s." },
            { q: "Which part of the brain controls balance and coordination?", a: "Cerebellum", s: "The <strong>Cerebellum</strong> (hindbrain) coordinates voluntary movements, balance, and posture." },
            { q: "The process of transferring heat without any medium is called:", a: "Radiation", s: "<strong>Radiation</strong> transfers heat through electromagnetic waves — no medium required (e.g., sunlight)." },
            { q: "Haemoglobin contains which metal?", a: "Iron (Fe)", s: "Haemoglobin contains <strong>iron (Fe)</strong> in its heme group, which binds oxygen." },
            { q: "Which is the most electronegative element?", a: "Fluorine (F)", s: "<strong>Fluorine</strong> has the highest electronegativity (3.98 on Pauling scale)." },
            { q: "What is the full form of ATP?", a: "Adenosine Triphosphate", s: "<strong>ATP (Adenosine Triphosphate)</strong> is the energy currency of the cell." },
            { q: "The planet closest to the Sun is:", a: "Mercury", s: "<strong>Mercury</strong> is the closest planet to the Sun, with an average distance of ~57.9 million km." },
            { q: "What is the phenomenon of apparent bending of a stick in water?", a: "Refraction", s: "The stick appears bent due to <strong>refraction</strong> of light at the water-air interface." },
            { q: "Which type of bond holds the two strands of DNA together?", a: "Hydrogen bonds", s: "The two DNA strands are held together by <strong>hydrogen bonds</strong> between complementary base pairs (A-T, G-C)." },
            { q: "The unit of work and energy is:", a: "Joule (J)", s: "Work = Force × Displacement. SI unit = <strong>Joule (J)</strong> = Newton × metre." },
            { q: "What is the chemical formula of Glucose?", a: "C₆H₁₂O₆", s: "Glucose is a simple sugar (monosaccharide) with formula <strong>C₆H₁₂O₆</strong>." },
            { q: "The focal length of a concave lens is:", a: "Negative", s: "By sign convention, a <strong>concave (diverging) lens</strong> has a negative focal length." },
            { q: "Which disease is caused by the deficiency of iodine?", a: "Goitre", s: "Iodine deficiency leads to <strong>Goitre</strong> — enlargement of the thyroid gland." },
            { q: "What is the chemical name of Washing Soda?", a: "Sodium Carbonate (Na₂CO₃·10H₂O)", s: "Washing Soda = <strong>Sodium Carbonate decahydrate (Na₂CO₃·10H₂O)</strong>." },
            { q: "The phenomenon of change in frequency of sound due to relative motion between source and observer is:", a: "Doppler Effect", s: "<strong>Doppler Effect</strong>: frequency increases as source approaches and decreases as it recedes." },
            { q: "Which part of the neuron receives signals?", a: "Dendrites", s: "<strong>Dendrites</strong> are the branched projections of neurons that receive electrochemical signals." },
            { q: "Which gas is commonly known as 'laughing gas'?", a: "Nitrous Oxide (N₂O)", s: "<strong>Nitrous Oxide</strong> is used as a mild anaesthetic and is nicknamed 'laughing gas' due to its euphoric effects." },
            { q: "The SI unit of electric resistance is:", a: "Ohm", s: "Electric resistance is measured in <strong>Ohm (Ω)</strong>, named after physicist Georg Simon Ohm." },
            { q: "Which vitamin deficiency causes night blindness?", a: "Vitamin A", s: "Deficiency of <strong>Vitamin A</strong> impairs the eye's ability to adapt to low light, causing night blindness." },
            { q: "The process by which plants lose water in vapour form through leaves is called:", a: "Transpiration", s: "<strong>Transpiration</strong> is the loss of water vapour from plant surfaces, mainly through stomata in leaves." },
            { q: "Which part of the human brain controls balance and coordination?", a: "Cerebellum", s: "The <strong>cerebellum</strong> is responsible for maintaining posture, balance, and coordinating voluntary movements." },
            { q: "pH value of a neutral solution at 25°C is:", a: "7", s: "A pH of <strong>7</strong> indicates a neutral solution, neither acidic nor basic, at 25°C." },
            { q: "Which alloy is used to make surgical instruments due to its corrosion resistance?", a: "Stainless Steel", s: "<strong>Stainless steel</strong>, an alloy of iron, chromium, and nickel, resists corrosion and is widely used for surgical tools." },
            { q: "The unit used to measure the loudness of sound is:", a: "Decibel (dB)", s: "Sound intensity/loudness is measured in <strong>decibels (dB)</strong> on a logarithmic scale." },
            { q: "Which blood group is known as the universal donor?", a: "O negative", s: "<strong>O negative</strong> blood lacks A, B, and Rh antigens, allowing it to be transfused to patients of any blood group in emergencies." },
            { q: "Photosynthesis in plants primarily takes place in which cell organelle?", a: "Chloroplast", s: "<strong>Chloroplasts</strong>, containing chlorophyll, are the site of photosynthesis where light energy is converted to chemical energy." }
        ];
